# M-a and 'M-a' key codes are same 

# unbind C-b as the prefix key and use F12 instead
unbind-key -n C-b   # C-b is used for navigation in terminal (emacs mode)
set -g prefix F12

# detach from present session
bind-key -n 'M-d' detach

# time delay in ms for displaying pane numbers
set -g display-panes-time 150

# split window
bind-key -n M-, split-window -h -c "#{pane_current_path}"  \; display-panes
bind-key -n M-/ split-window -v -c "#{pane_current_path}"  \; display-panes

# switch between different pane layouts
bind-key -n 'M-;' display-panes \; next-layout

# new window
bind-key -n M-. new-window -c "#{pane_current_path}" \; rename-window "-"

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
# the following mapping is not working in vim (works with nvim) if alt key is used
bind-key -n 'M-h' if-shell "$is_vim" 'send-keys M-h' 'select-pane -L' \; display-panes
bind-key -n 'M-j' if-shell "$is_vim" 'send-keys M-j' 'select-pane -D' \; display-panes
bind-key -n 'M-k' if-shell "$is_vim" 'send-keys M-k' 'select-pane -U' \; display-panes
bind-key -n 'M-l' if-shell "$is_vim" 'send-keys M-l' 'select-pane -R' \; display-panes
# pane switching when in copy-mode
bind-key -T copy-mode-vi 'M-h' select-pane -L \; display-panes
bind-key -T copy-mode-vi 'M-j' select-pane -D \; display-panes
bind-key -T copy-mode-vi 'M-k' select-pane -U \; display-panes
bind-key -T copy-mode-vi 'M-l' select-pane -R \; display-panes

# navigating windows
bind-key -n M-p previous-window
bind-key -n M-n next-window

# resizing panes
bind-key -n M-i resize-pane -U
bind-key -n M-u resize-pane -D
bind-key -n M-y resize-pane -L
bind-key -n M-o resize-pane -R

# copy-mode
bind-key -n M-m copy-mode

# copy pasting
bind-key -T copy-mode-vi v send -X begin-selection     # Begin selection in copy mode.
bind-key -T copy-mode-vi C-v send -X rectangle-toggle  # Begin selection in copy mode.
bind-key -T copy-mode-vi y send -X copy-pipe 'xclip -i -sel p -f | xclip -i -sel c'  # copy selected text to system clipboard

# set mouse mode on
set -g mouse on
# mouse selecting copies text into system clipboard and exit the copy-mode
# bind-key -n -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe 'xclip -i -sel p -f | xclip -i -sel c' \; send-keys -X cancel
# mouse selecting copies text into system clipboard and stays in copy-mode
bind-key -n -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe 'xclip -i -sel p -f | xclip -i -sel c'


set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0


set -g default-terminal "tmux-256color"
