#!/usr/bin/bash

width=1368
height=1024
vnc_password='kvngvikram'

a_random_number=1435

# from .desktop file
if [ -n "$1" ]; then  # if first input aurgument not empty
	if [ $1 -eq $a_random_number ]; then  # if first input arg is same as previously decided number
		xrandr --newmode "ipadvirtual"   53.25  "$width" 1408 1536 1704  "$height" 1027 1037 1045 +vsync
		xrandr --addmode VIRTUAL1 ipadvirtual
		xrandr --output VIRTUAL1 --right-of eDP1 --mode ipadvirtual
		x11vnc -clip "$width"x"$height"+1920+0 -multiptr -viewonly -passwd $vnc_password
		exit
	fi
fi

if [ ! -f /usr/share/X11/xorg.conf.d/20-intel.conf ]
then
	echo 20-intel.conf does not exist.
	echo Enabling
	echo creating 20-intel.conf and .desktop autstart entry. Logout to see changes.

	echo 'Section "Device"
			Identifier "intelgpu0"
			Driver "intel"
			Option "VirtualHeads" "2"
	EndSection' | sudo tee /usr/share/X11/xorg.conf.d/20-intel.conf > /dev/null

	echo "[Desktop Entry]
	Name=nvidia_second_virtual_screen
	Comment=To create second virtual VNC screen by switching to intel gpu from Nvidia.
	Exec=$(pwd)/$0 $a_random_number
	Terminal=false
	Type=Application
	Categories=Utility;" > $HOME/.config/autostart/tmp_nvidia_virt_screen.desktop

	# sudo pkill -u happy
	# sudo service lightdm restart
else
	echo 20-intel.conf exists!
	echo Disabling
	echo Deleting 20-intel.conf and .desktop autstart entry. Logout to see changes.

	sudo rm /usr/share/X11/xorg.conf.d/20-intel.conf
	rm ~/.config/autostart/tmp_nvidia_virt_screen.desktop

	xrandr --output VIRTUAL1 --off
	xrandr --delmode VIRTUAL1 ipadvirtual
	xrandr --rmmode ipadvirtual

	# sudo pkill -u happy
	# sudo service lightdm restart
fi
